-- La preferencia selectivo/integrativo (V12, V13) estaba fija. Pasa a ser una
-- pregunta complementaria configurable por cuestionario, con 2 o más
-- opciones, que se hace cuando el perfil destaca todos los estilos.
-- La release parte de una base vacía: no se migran las respuestas de prueba.
ALTER TABLE cuestionario DROP COLUMN pregunta_preferencia;
ALTER TABLE resultado_cuestionario DROP COLUMN preferencia_multimodal;
ALTER TABLE respuesta_capsula DROP COLUMN preferencia_multimodal;

CREATE TABLE pregunta_complementaria (
  cuestionario_id  bigint PRIMARY KEY REFERENCES cuestionario(id) ON DELETE CASCADE,
  titulo           varchar(150) NOT NULL,
  introduccion     varchar(500),
  enunciado        varchar(500) NOT NULL,
  nota             varchar(300)
);

CREATE TABLE opcion_complementaria (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuestionario_id        bigint NOT NULL REFERENCES pregunta_complementaria(cuestionario_id) ON DELETE CASCADE,
  orden                  int NOT NULL,
  texto                  varchar(200) NOT NULL,
  descripcion            varchar(1000),
  resultado              varchar(100) NOT NULL,
  resultado_descripcion  varchar(1000),
  UNIQUE (cuestionario_id, orden)
);

-- Al quitar una opción, quien la eligió queda sin declarar.
ALTER TABLE resultado_cuestionario
  ADD COLUMN opcion_complementaria_id bigint REFERENCES opcion_complementaria(id) ON DELETE SET NULL;
ALTER TABLE respuesta_capsula
  ADD COLUMN opcion_complementaria_id bigint REFERENCES opcion_complementaria(id) ON DELETE SET NULL;
