-- Esquema tal como lo dejo ddl-auto: update antes de adoptar Flyway (ola 3).
-- Extraido con pg_dump --schema-only del respaldo adela-pre-flyway-20260913-1405.
--
-- Una BD existente no lo ejecuta: baseline-on-migrate la marca como version 1 y
-- sigue desde V2. Solo corre en una BD vacia, que sin este archivo no arrancaba
-- porque V2 alteraba tablas que nadie habia creado.

CREATE TABLE public.cuestionario (
    id bigint NOT NULL,
    autor character varying(255) NOT NULL,
    descripcion character varying(1000) NOT NULL,
    nombre character varying(255) NOT NULL,
    siglas character varying(255) NOT NULL,
    version character varying(255) NOT NULL
);

ALTER TABLE public.cuestionario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuestionario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.estilo (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    valor_maximo double precision NOT NULL,
    valor_minimo double precision NOT NULL,
    cuestionario_id bigint NOT NULL
);

ALTER TABLE public.estilo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estilo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.estudiante (
    fecha_nacimiento date,
    genero smallint,
    email character varying(100) NOT NULL,
    CONSTRAINT estudiante_genero_check CHECK (((genero >= 0) AND (genero <= 2)))
);

CREATE TABLE public.grupo (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    profesor_id character varying(100) NOT NULL
);

ALTER TABLE public.grupo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.matricula (
    estudiante_id character varying(100) NOT NULL,
    curso_id integer NOT NULL
);

CREATE TABLE public.opcion (
    id bigint NOT NULL,
    orden integer NOT NULL,
    respuesta character varying(255) NOT NULL,
    valor double precision NOT NULL,
    categoria_id bigint NOT NULL,
    pregunta_id bigint NOT NULL
);

ALTER TABLE public.opcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pregunta (
    id bigint NOT NULL,
    opcion_multiple boolean NOT NULL,
    orden integer NOT NULL,
    pregunta character varying(255) NOT NULL,
    cuestionario_id bigint NOT NULL
);

ALTER TABLE public.pregunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pregunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.profesor (
    carrera character varying(50),
    estado_profesor character varying(100),
    email character varying(100) NOT NULL,
    rol_id integer,
    CONSTRAINT profesor_estado_profesor_check CHECK (((estado_profesor)::text = ANY (ARRAY[('ACTIVA'::character varying)::text, ('INACTIVA'::character varying)::text])))
);

CREATE TABLE public.resultado_cuestionario (
    id bigint NOT NULL,
    bloqueado boolean NOT NULL,
    fecha_aplicacion date,
    fecha_resolucion date,
    cuestionario_id bigint NOT NULL,
    estudiante_email character varying(100) NOT NULL,
    grupo_id integer
);

ALTER TABLE public.resultado_cuestionario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resultado_cuestionario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resultado_pregunta (
    id bigint NOT NULL,
    cuestionario_id bigint NOT NULL,
    opcion_id bigint NOT NULL
);

ALTER TABLE public.resultado_pregunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resultado_pregunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rol (
    id integer NOT NULL,
    descripcion character varying(100) NOT NULL
);

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.usuario (
    email character varying(100) NOT NULL,
    codigo character varying(8),
    estado character varying(255),
    nombre character varying(100),
    CONSTRAINT usuario_estado_check CHECK (((estado)::text = ANY (ARRAY[('ACTIVA'::character varying)::text, ('INCOMPLETA'::character varying)::text, ('INACTIVA'::character varying)::text])))
);

ALTER TABLE ONLY public.cuestionario
    ADD CONSTRAINT cuestionario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.estilo
    ADD CONSTRAINT estilo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT estudiante_pkey PRIMARY KEY (email);

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT grupo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_pkey PRIMARY KEY (estudiante_id, curso_id);

ALTER TABLE ONLY public.opcion
    ADD CONSTRAINT opcion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pregunta
    ADD CONSTRAINT pregunta_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_pkey PRIMARY KEY (email);

ALTER TABLE ONLY public.resultado_cuestionario
    ADD CONSTRAINT resultado_cuestionario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resultado_pregunta
    ADD CONSTRAINT resultado_pregunta_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uknswqpd1o31h81htx40ewmb41r UNIQUE (codigo);

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (email);

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT fk16g9x09tpqfc6g9wlngr7anld FOREIGN KEY (estudiante_id) REFERENCES public.estudiante(email);

ALTER TABLE ONLY public.resultado_cuestionario
    ADD CONSTRAINT fk4mpewuwfm5hab9m4re218ckp6 FOREIGN KEY (estudiante_email) REFERENCES public.estudiante(email);

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT fk4tv510v23t8c74yqe6d2l0nyu FOREIGN KEY (profesor_id) REFERENCES public.profesor(email);

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT fk4u1nxk2udlwqr63v08f3blpw3 FOREIGN KEY (rol_id) REFERENCES public.rol(id);

ALTER TABLE ONLY public.pregunta
    ADD CONSTRAINT fk5ugsgufj2joy66qbr52qooup3 FOREIGN KEY (cuestionario_id) REFERENCES public.cuestionario(id);

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT fk7j0lr8jvbfbb3j4h09j4fiig8 FOREIGN KEY (curso_id) REFERENCES public.grupo(id);

ALTER TABLE ONLY public.resultado_cuestionario
    ADD CONSTRAINT fk8ox5lvlb8tvcf9td22rtfe344 FOREIGN KEY (grupo_id) REFERENCES public.grupo(id);

ALTER TABLE ONLY public.resultado_pregunta
    ADD CONSTRAINT fkbi6a0v7xq6r6li4aekw9yo2su FOREIGN KEY (cuestionario_id) REFERENCES public.resultado_cuestionario(id);

ALTER TABLE ONLY public.opcion
    ADD CONSTRAINT fkigucw9du5jqhwtyvj97al7phn FOREIGN KEY (categoria_id) REFERENCES public.estilo(id);

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT fkjgs06amcheti95wxjdfi3gwsk FOREIGN KEY (email) REFERENCES public.usuario(email);

ALTER TABLE ONLY public.resultado_pregunta
    ADD CONSTRAINT fkk1eacoodcyvtwq4qw5rqmk2gj FOREIGN KEY (opcion_id) REFERENCES public.opcion(id);

ALTER TABLE ONLY public.opcion
    ADD CONSTRAINT fkmbls7mhuqgs6v9ejkyehe93k8 FOREIGN KEY (pregunta_id) REFERENCES public.pregunta(id);

ALTER TABLE ONLY public.estilo
    ADD CONSTRAINT fkn11b427y7odj3yrofxbwie6lw FOREIGN KEY (cuestionario_id) REFERENCES public.cuestionario(id);

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT fkoj1rr4i22j09dcqv27vo9wp1w FOREIGN KEY (email) REFERENCES public.usuario(email);

ALTER TABLE ONLY public.resultado_cuestionario
    ADD CONSTRAINT fkpse5e7u5tagjs9lblwftougbk FOREIGN KEY (cuestionario_id) REFERENCES public.cuestionario(id);
