-- Capsulas: enlace publico a un cuestionario para participantes sin cuenta.
-- Tablas propias en lugar de reutilizar resultado_cuestionario: alli el
-- estudiante es obligatorio y forma parte de la unicidad de la asignacion, y
-- relajarlo afectaria a todas las consultas de grupos y reportes.
create table capsula (
    id                  bigint generated by default as identity primary key,
    codigo              varchar(8)   not null unique,
    nombre              varchar(100) not null,
    profesor_email      varchar(100) not null references profesor(email) on delete cascade,
    cuestionario_id     bigint       not null references cuestionario(id),
    modo_identificacion varchar(10)  not null check (modo_identificacion in ('ANONIMO', 'NOMBRE')),
    abierta             boolean      not null default true,
    creada_en           timestamptz  not null
);
create index capsula_profesor_idx on capsula(profesor_email);

-- codigo es la credencial con la que el participante vuelve a su resultado;
-- intento lo genera el cliente para que un reenvio no cree una segunda fila.
create table respuesta_capsula (
    id            bigint generated by default as identity primary key,
    capsula_id    bigint      not null references capsula(id) on delete cascade,
    codigo        varchar(12) not null unique,
    intento       uuid        not null,
    nombre        varchar(60),
    respondida_en timestamptz not null,
    unique (capsula_id, intento)
);

create table respuesta_capsula_opcion (
    respuesta_id bigint not null references respuesta_capsula(id) on delete cascade,
    opcion_id    bigint not null references opcion(id),
    primary key (respuesta_id, opcion_id)
);
