-- Motor de calificacion v2: configuracion de la interpretacion por cuestionario
-- y obligatoriedad por pregunta. Los rangos legados (estilo.valor_minimo y
-- valor_maximo) se retiran en otra migracion, cuando sus lectores pasen al motor.
alter table cuestionario
    add column esquema_interpretacion varchar(30) not null default 'NINGUNA'
        check (esquema_interpretacion in ('NINGUNA', 'BAREMO', 'RELATIVO', 'RELATIVO_ESCALONADO')),
    add column delta_relativo double precision not null default 10,
    add column es_ipsativo    boolean          not null default false;

-- Antes la obligatoriedad se deducia del formato: unica obligatoria, multiple no.
alter table pregunta add column obligatoria boolean not null default true;
update pregunta set obligatoria = not opcion_multiple;

-- Niveles de un estilo (baremo del manual o umbrales fijos).
create table banda_interpretacion (
    id              bigint generated by default as identity primary key,
    estilo_id       bigint           not null references estilo(id) on delete cascade,
    escala          varchar(10)      not null check (escala in ('BRUTO', 'POMP')),
    limite_inferior double precision not null,
    limite_superior double precision not null,
    etiqueta        varchar(60)      not null,
    orden           integer          not null,
    check (limite_inferior <= limite_superior),
    unique (estilo_id, escala, orden)
);
create index banda_interpretacion_estilo_idx on banda_interpretacion(estilo_id);

-- Distancia de paso para RELATIVO_ESCALONADO (VARK).
create table escalon_relativo (
    id              bigint generated by default as identity primary key,
    cuestionario_id bigint           not null references cuestionario(id) on delete cascade,
    total_min       double precision not null,
    total_max       double precision not null,
    distancia       double precision not null,
    unique (cuestionario_id, total_min)
);
